### ISSUE TITLE
Release a new version targeting svg-path-lowlevel 4.0.0?

### ISSUE THREAD

**Issue by etaque** [folkertdev/one-true-path-experiment#8]
Hello Folkert, 
First, thank you for this great package!
We're hitting the bug solved by this PR on svg-path-lowlevel: https://github.com/folkertdev/svg-path-lowlevel/pull/2
Would you mind releasing a new version targeting 4.0.0?

Cheers and thanks again,
Emilien

**Comment by folkertdev** [comment]
The `6.0.0` release includes that PR now (and an additional number parsing fix)

**Comment by etaque** [comment]
Great! Thanks, and have a nice day.
